title: Tourism Mongolia # your site title
author: Sunpath Mongolia
email: darmaa.am@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Tourism Mongolia by Sunpath Mongolia
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jantsankhorloo.github.io/sleek" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:  # replace with your_twitter_username or comment to remove link from footer
github_username:   # replace with your_github_username or comment to remove link from footer
instagram_username:  # replace with your_instagram_username or comment to remove link from footer
social:
  name: Your Name
  links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/in/
    - https://plus.google.com/



disqus:
  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
